### ISSUE TITLE
PEG.js support

### ISSUE THREAD

**Issue by bd82** [rdking/chevrotain-ebnf#1]
@rdking wrote:

> Ok. It's been released. The patch updates are just minor documentation changes. Do you think it would be worthwhile to write one for PEGjs grammar as well? When I started working on this new language 2 weeks ago, I thought to write the compiler for it using PEG. But that was before I encountered Chevrotain and checked its reviews.

Do you mean convert your EBNF notation to **either** Chevrotain Parser or a PEG.js parser?

**Comment by rdking** [comment]
No I mean produce a new module called chevrotain-pegjs that does exactly the same thing this module does, except for peg's variation of ebnf.

**Comment by rdking** [comment]
Basically, I'm thinking of creating a bridge for those coming from PEG.js to try Chevrotain without having to re-tool their grammar files any more than necessary.

**Comment by bd82** [comment]
This sounds like: https://github.com/SAP/chevrotain/issues/841
And would be very useful as a starting point for someone converting a grammar from PEG.js to Chevrotain.

But there are some "gotcha's" which I will explain below.

**Comment by rdking** [comment]
That's more or less the intent.

**Comment by bd82** [comment]
Such a conversion tool may not be able to handle all cases for example:
- PEG.js is a scannerless parser, it does not have a tokenization phase.
  This means it could make "scanning" decision based on grammar context which is something Chevrotain cannot do at this time.
  - [RegExp vs Divison ambiguity in EcmaScript](https://github.com/sweet-js/sweet-core/wiki/design)
- What I mentioned earlier about the importance of Tokens order and potentially advanced Tokens configuration (e.g longer_alt).
- PEG.js does not allow ignoring tokens(Chevrotain does...), but in many languages Whitespace is completely ignored
  so translating PEG.js directly to Chevrotain may not endup with the most optimal grammar.

So I think this would be highly useful, but would have to include a large amount of documentation (I can help with that)
for edge cases and best practices, because such a tool would do 90-95% of the work, but a human may still be required in many cases to process the output... 😄

**Comment by rdking** [comment]
Given that I only ever expected the pegjs module to act as a starting point for people wanting to switch to Chevrotain, I think those limitations are more than acceptable. Anyone manually doing the conversion would need to take those same factors into consideration, so it's no big loss.

**Comment by bd82** [comment]
Also consider you may not need to actually parse the peg.js grammar.
PEG.js is already doing it, if you can hack into their internal representation of their grammar
you could convert it directly to a Chevrotain GAST.

That would simplify the task...

**Comment by bd82** [comment]
> Given that I only ever expected the pegjs module to act as a starting point for people wanting to switch to Chevrotain, I think those limitations are more than acceptable. Anyone manually doing the conversion would need to take those same factors into consideration, so it's no big loss.

Yep, you are correct, but that is why the documentation part of such efforts will be important (I will assist).

**Comment by rdking** [comment]
I've got v1.1.1 out the door. So unless you see some problem with it that I missed, I'll duplicate this repo and create chevrotain-pegjs. Fortunately, it's not that different. Unfortunately, it's just different enough to warrant a separate module.

**Comment by rdking** [comment]
I just thought of the most hilarious approach to doing this. If I can figure out the EBNF for PEGjs grammar, then I can feed it to this module to produce the parser module for chevrotain-pegjs. It's just a matter of whether or not an LL(1) EBNF grammar exists for PEGjs.

**Comment by bd82** [comment]
That would be amusing indeed but highly fragile 😄 .

I still suspect the most robust manner would be to **avoid parsing** altogether
and convert the internal pegjs representation to a Chevrotain grammar representation.
- Assuming the internal pegjs representation is accessible...

**Comment by rdking** [comment]
It may not be as fragile as you think. The only major difference that I see between PEG and Chevrotain is that PEG is a greedy parser without a tokenizer. If I can reduce a PEG grammar's terminals to a series of characters, then Chevrotain's tokenizer can be eliminated as a problem. The greediness of PEG isn't really an issue either given that Chevrotain's Lexer works in the same way. `( "A" | "AB" )` would never fully parse "AB" in Chevrotain or PEG. However `"A" [ "B" ]` in EBNF and `"A" "B"?` in PEG would parse for both engines.

The next biggest difference is that PEG adds a weird syntax for adding visitor logic. If I can get chevrotain-pegjs to generate a visitor to include that logic, all the better. This is where the real work is going to be, and where any fragility is likely to show up. However, at that point, it's time for the developer to start tweaking anyway.

If you wanna talk more about how this should be done, we can do so in [chevrotain-pegjs](https://github.com/rdking/chevrotain-pegjs).

**Comment by bd82** [comment]
I meant robust in terms of if PEGs adds new syntax constructs their internal data structure may not change
but the chevrotain-pegjs package would still need to be updated.

I will add feedback to the new repo you created.

**Comment by bd82** [comment]
I think any useful feedback will only happen once I get around to 
integrating an example using  the peg.js related package you created into
the Chevrotain repo.

https://github.com/SAP/chevrotain/issues/841

And thanks for this packages 😄

**Comment by rdking** [comment]
Don't do that just yet. Wait until I'm ready to release it to npm. Right now I'm still trying to work out the grammar details. I've already got a grammar that "looks right", but something is still wrong with it as it doesn't parse yet. I end up with an error in the lexer about charCodeAt not being a function.

**Comment by bd82** [comment]
It will take a while before I get to that issue anyways.
Even though it is a strategic concern as it allows an easier migration path for existing
projects... 😢 

I am just busy with other projects at this time..
- https://github.com/bd82/toml-tools
- https://github.com/jhipster/prettier-java
