### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by simon-p-r** [rdking/chevrotain-ebnf#3]
Hi

I have found a couple of issues when using this module, in the following lines the value should be **Vocabulary** instead of **Variable**

    https://github.com/rdking/chevrotain-ebnf/blob/master/index.js#L211   
    https://github.com/rdking/chevrotain-ebnf/blob/master/index.js#L218

Also on this line **tokens.errors** should be **lexResult.errors**

    https://github.com/rdking/chevrotain-ebnf/blob/master/index.js#L302

I can do a PR if you want.

Thanks

**Comment by rdking** [comment]
Sorry for the delay. It's fixed and published now. Nice catch. I've really got to take some time to write proper unit tests for this.
